### ISSUE TITLE
Add test assertion to make sure we don't install multiverse packages 

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/bionic-base-stack#32]
In #31  we re-added the `multiverse` package source to the stack images with the intention of enabling use cases that might need packages from this location.

We do not want to ship any packages from `multiverse` in the stacks themselves, as explained in the linked PR. To prevent against this in the future, we should add a test assertion to the suite that checks that no packages come from the `multiverse` repository.

**Comment by sophiewigmore** [comment]
After a preliminary investigation, it seemed like running something like `apt policy <pkg>` name from each installed package would potentially give us metadata about where the dependency came from. However, as the stack exists now, this metadata did not exist so we may need to run some other commands first to be able to get this information.

**Comment by robdimsdale** [comment]
This is complete via https://github.com/paketo-buildpacks/bionic-base-stack/commit/8012cd9d168ec058cf2f33a8c1cacc5d07f4a9fc.
